name: wurigiri
description: couple app
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # StateManager
  get:

  # Firebase
  firebase_core:
  cloud_firestore:
  firebase_storage: ^11.0.10

  # LocalDB
  hive_flutter:
  hive:

  # Utils
  equatable:
  platform_device_id: ^1.0.1
  badges:
  image_picker: ^0.8.6+1
  image_cropper: ^3.0.1
  flutter_image_compress: ^1.0.0-nullsafety
  intl:
  cached_network_image: ^3.2.3
  auto_size_text_field: ^2.2.1
  reorderables:
  table_calendar: ^3.0.9
  flutter_slidable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^1.2.1
flutter:
  uses-material-design: true
  fonts:
    - family: HiMelody
      fonts:
        - asset: fonts/HiMelody-Regular.ttf
  assets:
    - assets/
